version: '3'
services:
  rene:
    build: .
    working_dir: '/rene'
    volumes:
      - ./src:/rene/src
      - ./data:/rene/data
    environment:
      - 'PYTHONPATH=/rene/src'
    entrypoint: python3 src/rest_wrapper.py #streamlit run src/st_rene.py   
    ports:
      - "5000:5000"
  st:
    build: .
    working_dir: '/rene'
    volumes:
      - ./src:/rene/src
      - ./data:/rene/data
    environment:
      - 'PYTHONPATH=/rene/src'
    entrypoint: streamlit run src/st_rene.py   
    ports:
      - "8501:8501"